translate Spanish strings:
    old "{#weekday}Monday"
    new "Lunes"
    old "{#weekday}Tuesday"
    new "Martes"
    old "{#weekday}Wednesday"
    new "Miércoles"
    old "{#weekday}Thursday"
    new "Jueves"
    old "{#weekday}Friday"
    new "Viernes"
    old "{#weekday}Saturday"
    new "Sábado"
    old "{#weekday}Sunday"
    new "Domingo"
    old "{#weekday_short}Mon"
    new "Lun."
    old "{#weekday_short}Tue"
    new "Mar."
    old "{#weekday_short}Wed"
    new "Mié."
    old "{#weekday_short}Thu"
    new "Jue."
    old "{#weekday_short}Fri"
    new "Vie."
    old "{#weekday_short}Sat"
    new "Sab."
    old "{#weekday_short}Sun"
    new "Dom."
    old "{#month}January"
    new "Enero"
    old "{#month}February"
    new "Febrero"
    old "{#month}March"
    new "Marzo"
    old "{#month}April"
    new "Abril"
    old "{#month}May"
    new "Mayo"
    old "{#month}June"
    new "Junio"
    old "{#month}July"
    new "Julio"
    old "{#month}August"
    new "Agosto"
    old "{#month}September"
    new "Septiembre"
    old "{#month}October"
    new "Octubre"
    old "{#month}November"
    new "Noviembre"
    old "{#month}December"
    new "Diciembre"
    old "{#month_short}Jan"
    new "Ene."
    old "{#month_short}Feb"
    new "Feb."
    old "{#month_short}Mar"
    new "Mar."
    old "{#month_short}Apr"
    new "Abr."
    old "{#month_short}May"
    new "May."
    old "{#month_short}Jun"
    new "Jun."
    old "{#month_short}Jul"
    new "Jul."
    old "{#month_short}Aug"
    new "Ago."
    old "{#month_short}Sep"
    new "Sep."
    old "{#month_short}Oct"
    new "Oct."
    old "{#month_short}Nov"
    new "Nov."
    old "{#month_short}Dec"
    new "Dic."
    old "%b %d, %H:%M"
    new "%d %b, %H:%M"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%A, %B %d %Y, %H:%M"
    old "Quick save complete."
    new "Grabar rápido completo."
    old "Image [index] of [count] locked."
    new "Imagen [index] de [count] bloqueada."
    old "Graphics Acceleration"
    new "Aceleración gráfica"
    old "Automatically Choose"
    new "Escoger automáticamente"
    old "Force Angle/DirectX Renderer"
    new "Forzar 'Angle/DirectX Renderer'"
    old "Force OpenGL Renderer"
    new "Forzar 'OpenGL Renderer'"
    old "Force Software Renderer"
    new "Forzar 'Software Renderer'"
    old "Changes will take effect the next time this program is run."
    new "Los cambios se aplicarán la próxima vez que el programa se ejecute."
    old "Performance Warning"
    new "Aviso de funcionamiento"
    old "This computer is using software rendering."
    new "Este ordenador usa 'software rendering'."
    old "This computer is not using shaders."
    new "Este ordenador no usa 'shaders'."
    old "This computer is displaying graphics slowly."
    new "Este ordenador muestra los gráficos lentamente."
    old "This computer has a problem displaying graphics: [problem]."
    new "Este ordenador tiene un problema mostrando los gráficos: [problem]."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display. Updating DirectX could fix this problem."
    new "Los controladores gráficos pueden estar obsoletos o no funcionar adecuadamente. Esto puede conllevar que los gráficos se muestren lenta o incorrectamente. Actualizar DirectX puede solucionar este problema."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "Los controladores gráficos pueden estar obsoletos o no funcionar adecuadamente. Esto puede conllevar que los gráficos se muestren lenta o incorrectamente."
    old "Update DirectX"
    new "Actualizar DirectX"
    old "Continue, Show this warning again"
    new "Continuar. Mostrar este aviso de nuevo"
    old "Continue, Don't show warning again"
    new "Continuar. No mostrar este aviso de nuevo"
    old "Updating DirectX."
    new "Actualizando DirectX."
    old "DirectX web setup has been started. It may start minimized in the taskbar. Please follow the prompts to install DirectX."
    new "La instalación web de DirectX ha comenzado. Puede haber iniciado minimizada en la barra de tareas. Siga las instrucciones para instalar DirectX."
    old "{b}Note:{/b} Microsoft's DirectX web setup program will, by default, install the Bing toolbar. If you do not want this toolbar, uncheck the appropriate box."
    new "{b}Nota:{/b} El programa de instalación de DirectX de Microsoft instalará, por defecto, la barra Bing. Si no desea esta barra, desactive la casilla correspondiente."
    old "When setup finishes, please click below to restart this program."
    new "Cuando la instalación acabe, haga clic abajo para reiniciar el programa."
    old "Restart"
    new "Reiniciar"
    old "Saved screenshot as %s."
    new "Captura de pantalla guardada como %s."
    old "Are you sure?"
    new "¿Seguro?"
    old "Are you sure you want to delete this save?"
    new "¿Seguro que desea borrar esta partida?"
    old "Are you sure you want to overwrite your save?"
    new "¿Seguro que desea sobreescribir esta partida?"
    old "The next step is an important scene. Do you want to save here?"
    new "El siguiente paso es una escena importante. ¿Quieres guardar aquí?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "Al cargar se perderá el progreso no guardado.\n¿Seguro que desea hacer esto?"
    old "Are you sure you want to quit?"
    new "¿Seguro que desea salir?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "¿Seguro que desea volver al menú principal?\nSe perderá el progreso no guardado."
    old "Are you sure you want to skip to unseen dialogue or the next choice?"
    new "¿Seguro que desea saltar hasta el diálogo no visto o la próxima elección?"
    old "Are you sure you want to end the replay?"
    new "¿Seguro que quieres finalizar la repetición?"
    old "Skip Mode"
    new "Modo Salto"
    old "Fast Skip Mode"
    new "Modo salto rápido"
    old "An exception has occurred."
    new "Ha sucedido una excepción."
    old "Rollback"
    new "Volver atrás"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "Intenta volver a un momento anterior y permite guardar o escoger una opción diferente."
    old "Ignore"
    new "Ignorar"
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "Ignora la excepción y permite continuar. Suele conllevar más errores."
    old "Reload"
    new "Recargar"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "Recarga el juego del disco, guardando y restaurando la partida si es posible."
    old "Open Traceback"
    new "Abrir rastreo"
    old "Opens the traceback.txt file in a text editor."
    new "Abre el archivo de rastreo 'traceback.txt' en un editor de texto."
    old "Quits the game."
    new "Sale del juego."
    old "Parsing the script failed."
    new "Error en el análisis del código."
    old "Open Parse Errors"
    new "Abre errores de análisis"
    old "Opens the errors.txt file in a text editor."
    new "Abre el archivo de errores, 'errors.txt', en un editor de texto."
    old "Self-voicing enabled. Press 'v' to disable."
    new "Voz automática activada. Presiona 'v' para desactivarla."
    old "Self-voicing disabled."
    new "Voz automática desactivada."