translate Spanish strings:
    old "Load"
    new "Cargar"
    old "Left arrow key: Yes, Right arrow key: No."
    new "Tecla de flecha izquierda: Sí, Tecla de flecha derecha: No."
    old "Left arrow key: Previous, Right arrow key: Next."
    new "Tecla de flecha izquierda: Anterior, Tecla de flecha derecha: Siguiente."
    old "{font=[gui.fontawesome]}{/font} Basic Settings"
    new "{font=[gui.fontawesome]}{/font} Ajustes básicos"
    old "{font=[gui.fontawesome]}{/font} About"
    new "{font=[gui.fontawesome]}{/font} Acerca de"
    old "{font=[gui.fontawesome]}{/font} Help"
    new "{font=[gui.fontawesome]}{/font} Ayuda"
    old "{font=[gui.fontawesome]}{/font} Characters"
    new "{font=[gui.fontawesome]}{/font} Personajes"
    old "{font=[gui.fontawesome]}{/font} Concept"
    new "{font=[gui.fontawesome]}{/font} Concepto"
    old "{font=[gui.fontawesome]}{/font} Diary"
    new "{font=[gui.fontawesome]}{/font} Agenda"
    old "{font=[gui.fontawesome]}{/font} Gallery"
    new "{font=[gui.fontawesome]}{/font} Galería"
    old "{font=[gui.fontawesome]}{/font} Music"
    new "{font=[gui.fontawesome]}{/font} Música"
    old "{font=[gui.fontawesome]}{/font} Replay"
    new "{font=[gui.fontawesome]}{/font} Repetición"
    old "{font=[gui.fontawesome]}{/font} Medals"
    new "{font=[gui.fontawesome]}{/font} Medallas"
    old "{font=[gui.fontawesome]}{/font} Refresh"
    new "{font=[gui.fontawesome]}{/font} Refrescar"
    old "{font=[gui.fontawesome]}{/font} Window"
    new "{font=[gui.fontawesome]}{/font} Ventana"
    old "{font=[gui.fontawesome]}{/font} Fullscreen"
    new "{font=[gui.fontawesome]}{/font} Pant. completa"
    old "{font=[gui.fontawesome]}{/font} Save"
    new "{font=[gui.fontawesome]}{/font} Guardar"
    old "{font=[gui.fontawesome]}{/font} Start Reading"
    new "{font=[gui.fontawesome]}{/font} Comenzar"
    old "{font=[gui.fontawesome]}{/font} Load"
    new "{font=[gui.fontawesome]}{/font} Cargar"
    old "{font=[gui.fontawesome]}{/font} Configuration"
    new "{font=[gui.fontawesome]}{/font} Opciones"
    old "{font=[gui.fontawesome]}{/font} DLC&MOD"
    new "{font=[gui.fontawesome]}{/font} DLC y MOD"
    old "{font=[gui.fontawesome]}{/font} End Replay"
    new "{font=[gui.fontawesome]}{/font} Fin repetición"
    old "{font=[gui.fontawesome]}{/font} Main Menu"
    new "{font=[gui.fontawesome]}{/font} Menú principal"
    old "{font=[gui.fontawesome]}{/font} Quit"
    new "{font=[gui.fontawesome]}{/font} Salir"
    old "{font=[gui.fontawesome]}{/font} Done"
    new "{font=[gui.fontawesome]}{/font} Hecho"
    old "{font=[gui.fontawesome]}{/font} Return"
    new "{font=[gui.fontawesome]}{/font} Volver"
    old "{font=[gui.fontawesome]}{/font} Yes"
    new "{font=[gui.fontawesome]}{/font} Sí"
    old "{font=[gui.fontawesome]}{/font} No"
    new "{font=[gui.fontawesome]}{/font} No"
    old "Version [config.version!t]\n"
    new "Versión [config.version!t]\n"
    old "Created with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]\n"
    new "Created with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]\n"
    old "empty slot"
    new "vacío"
    old "{#auto_page}A"
    new "{#auto_page}A"
    old "{#quick_page}Q"
    new "{#quick_page}R"
    old "Page {}"
    new "Página {}"
    old "{font=[gui.fontawesome]}{/font} Display"
    new "{font=[gui.fontawesome]}{/font} Pantalla"
    old "{font=[gui.fontawesome]}{/font} Rollback Side"
    new "{font=[gui.fontawesome]}{/font} Lado de retroceso"
    old "{font=[gui.fontawesome]}{/font} Enable"
    new "{font=[gui.fontawesome]}{/font} Habilitar"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} Desactivar"
    old "{font=[gui.fontawesome]}{/font} Left"
    new "{font=[gui.fontawesome]}{/font} Izquierda"
    old "{font=[gui.fontawesome]}{/font} Right"
    new "{font=[gui.fontawesome]}{/font} Derecha"
    old "{font=[gui.fontawesome]}{/font} Skip"
    new "{font=[gui.fontawesome]}{/font} Saltar"
    old "{font=[gui.fontawesome]}{/font} Seen Text"
    new "{font=[gui.fontawesome]}{/font} Texto visto"
    old "{font=[gui.fontawesome]}{/font} After Choices"
    new "{font=[gui.fontawesome]}{/font} Tras opciones"
    old "{font=[gui.fontawesome]}{/font} Transitions"
    new "{font=[gui.fontawesome]}{/font} Transiciones"
    old "{font=[gui.fontawesome]}{/font} Text Speed"
    new "{font=[gui.fontawesome]}{/font} Veloc. texto"
    old "{font=[gui.fontawesome]}{/font} Auto-Forward Time"
    new "{font=[gui.fontawesome]}{/font} Veloc. auto-avance"
    old "{font=[gui.fontawesome]}{/font} Music Volume"
    new "{font=[gui.fontawesome]}{/font} Volumen música"
    old "{font=[gui.fontawesome]}{/font} Sound Volume"
    new "{font=[gui.fontawesome]}{/font} Volumen sonido"
    old "{font=[gui.fontawesome]}{/font} Test"
    new "{font=[gui.fontawesome]}{/font} Prueba"
    old "{font=[gui.fontawesome]}{/font} Voice Volume"
    new "{font=[gui.fontawesome]}{/font} Volumen voz"
    old "{font=[gui.fontawesome]}{/font} Mute All"
    new "{font=[gui.fontawesome]}{/font} Silencia todo"
    old "The dialogue history is empty."
    new "El historial está vacío."
    old "{font=[gui.fontawesome]}{/font} Total"
    new "{font=[gui.fontawesome]}{/font} Total"
    old "{font=[gui.fontawesome]}{/font} Characters +2"
    new "{font=[gui.fontawesome]}{/font} Personajes +2"
    old "{font=[gui.fontawesome]}{/font} Music +1"
    new "{font=[gui.fontawesome]}{/font} Música +1"
    old "{font=[gui.fontawesome]}{/font} Replay +1"
    new "{font=[gui.fontawesome]}{/font} Repetición +1"
    old "{font=[gui.fontawesome]}{/font} Replay +3"
    new "{font=[gui.fontawesome]}{/font} Repetición +3"
    old "{font=[gui.fontawesome]}{/font} Characters +1"
    new "{font=[gui.fontawesome]}{/font} Personajes +1"
    old "{font=[gui.fontawesome]}{/font} Concept +1"
    new "{font=[gui.fontawesome]}{/font} Concepto +1"
    old "{font=[gui.fontawesome]}{/font} Gallery +3"
    new "{font=[gui.fontawesome]}{/font} Galería +3"
    old "{font=[gui.fontawesome]}{/font} Gallery +2"
    new "{font=[gui.fontawesome]}{/font} Galería +2"
    old "{font=[gui.fontawesome]}{/font} Music +2"
    new "{font=[gui.fontawesome]}{/font} Música +2"
    old "{font=[gui.fontawesome]}{/font} Gallery +1"
    new "{font=[gui.fontawesome]}{/font} Galería +1"
    old "{font=[gui.fontawesome]}{/font} Concept +2"
    new "{font=[gui.fontawesome]}{/font} Concepto +2"
    old "{font=[gui.fontawesome]}{/font} Diary +15"
    new "{font=[gui.fontawesome]}{/font} Agenda +15"
    old "{font=[gui.fontawesome]}{/font} Diary +1"
    new "{font=[gui.fontawesome]}{/font} Agenda +1"
    old "Back to the bridge!"
    new "De vuelta al puente!"
    old "Discouraged Workers Extras"
    new "Extras de Trabajadores Desalentados"
    old "{font=[gui.fontawesome]}{/font} Open"
    new "{font=[gui.fontawesome]}{/font} Abierto"
    old "{font=[gui.fontawesome]}{/font} Gift"
    new "{font=[gui.fontawesome]}{/font} Regalo"
    old "{font=[gui.fontawesome]}{/font} Delete"
    new "{font=[gui.fontawesome]}{/font} Borrar"
    old "{font=[gui.fontawesome]}{/font} Install"
    new "{font=[gui.fontawesome]}{/font} Instalar"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} Añadir a la cesta"
    old "{font=[gui.fontawesome]}{/font} Start"
    new "{font=[gui.fontawesome]}{/font} Comenzar"
    old "Original Sound Track"
    new "Banda Sonora Original de Trabajadores Desalentados"
    old "{font=[gui.fontawesome]}{/font} Manual"
    new "{font=[gui.fontawesome]}{/font} Manual"
    old "Digital Art Book"
    new "Libro de arte digital de Trabajadores Desalentados"
    old "{font=[gui.fontawesome]}{/font} View"
    new "{font=[gui.fontawesome]}{/font} Ver"
    old "Digital Concept Book"
    new "Libro de concepto digital de Trabajadores Desalentados"
    old "MOD Creator Development Kit"
    new "Kit de desarrollo de creador de MOD"
    old "Back to the Basic"
    new "Volver a lo básico"
    old "Tarot PNP Pack"
    new "Tarot PNP Paquete"
    old "Please wait for more update."
    new "Por favor, espere por más de actualización."
    old "Skipping"
    new "Saltando"
    old "{font=[gui.fontawesome]}{/font} Language"
    new "{font=[gui.fontawesome]}{/font} Idioma"
    old "{font=[gui.fontawesome]}{/font} Vibrate"
    new "{font=[gui.fontawesome]}{/font} Vibrar"
    old "{font=[gui.fontawesome]}{/font} Controller"
    new "{font=[gui.fontawesome]}{/font} Controlador"
    old "{font=[gui.fontawesome]}{/font} Disable"
    new "{font=[gui.fontawesome]}{/font} Inhabilitar"
    old "Do not display any Controller images."
    new "No muestra las imágenes del controlador."
    old "{font=[gui.fontawesome]}{/font} Steam Controller"
    new "{font=[gui.fontawesome]}{/font} Steam controlador"
    old "Display the Steam Controller images."
    new "Muestra las imágenes del controlador Steam."
    old "{font=[gui.fontawesome]}{/font} General Gamepad"
    new "{font=[gui.fontawesome]}{/font} Gamepad general"
    old "{font=[gui.fontawesome]}{/font} {s}OUYA Controller{/s}"
    new "{font=[gui.fontawesome]}{/font} {s}OUYA controlador{/s}"
    old "Display the Xbox Controller images."
    new "Muestra las imágenes del controlador Xbox."
    old "Display the OUYA Controller images."
    new "Muestra las imágenes del controlador OUYA."
    old "{font=[gui.fontawesome]}{/font} Tic disorder"
    new "{font=[gui.fontawesome]}{/font} Trastorno tic"
    old "This will activate Ga-yeon's tic disorder."
    new "Esto activará el trastorno de Ga-yeon."
    old "This will deactivate Ga-yeon's tic disorder."
    new "Esto desactivará el trastorno de Ga-yeon."
    old "{font=[gui.fontawesome]}{/font} Epilepsy-friendly"
    new "{font=[gui.fontawesome]}{/font} Epilepsia-amigable"
    old "This will disable some screen effects for people who have epilepsy or similar photosensitive disorders."
    new "This will disable some screen effects for people who have epilepsy or similar photosensitive disorders."
    old "{font=[gui.fontawesome]}{/font} Blind-friendly"
    new "{font=[gui.fontawesome]}{/font} Ciego-amigable"
    old "This will activate the blind-friendly features with the self-voicing feature."
    new "Esto activará las funciones amigables a los débiles visuales con la función de auto-expresado."
    old "This will disable the blind-friendly features."
    new "Esto inhabilitará las funciones amigables a los débiles visuales."
    old "Reset"
    new "Reajustar"
    old "Directing, Design, Programming, Music, Sound, Writing, UI Design, Background CG, Object Sprites, Packaging, Video, Website -From April 21, 2013"
    new "Directing, Design, Programming, Music, Sound, Writing, UI Design, Background CG, Object Sprites, Packaging, Video, Website -From April 21, 2013"
    old "Animation, Character Sprites, CG Sprites -From March 10, 2015"
    new "Animation, Character Sprites, CG Sprites -From March 10, 2015"
    old "English Translation Adviser -June 3, 2015~July 1, 2017"
    new "English Translation Adviser -June 3, 2015~July 1, 2017"
    old "English Translator -April 11, 2015~June 10, 2016"
    new "English Translator -April 11, 2015~June 10, 2016"
    old "Chinese Translator -July 25, 2016~February 10, 2018"
    new "Chinese Translator -July 25, 2016~February 10, 2018"
    old "Russian Translator -August 28, 2016~December 7, 2017"
    new "Russian Translator -August 28, 2016~December 7, 2017"
    old "Project Leader in Spanish, Spanish Translator -From May 29, 2017"
    new "Encargado del Proyecto A Español, Localización en español -Desde el 29 de mayo de 2017"
    old "Spanish Editor -From May 29, 2017"
    new "Editor español -Desde el 29 de mayo de 2017"
    old "Spanish Translator -From May 29, 2017"
    new "Localización en español -Desde el 29 de mayo de 2017"
    old "Epilepsy Adviser -November 15, 2015~November 20, 2015"
    new "Epilepsy Adviser -November 15, 2015~November 20, 2015"
    old "Male sprites, CG sprites -April 8, 2015~September 13, 2015"
    new "Male sprites, CG sprites -April 8, 2015~September 13, 2015"
    old "Unofficial Demo Sprites -January 5, 2015~February 25, 2015"
    new "Unofficial Demo Sprites -January 5, 2015~February 25, 2015"
    old "English Demo Translation Adviser -June 3, 2015~June 14, 2015"
    new "English Demo Translation Adviser -June 3, 2015~June 14, 2015"
    old '{font=[gui.fontawesome]}{/font} Old Version'
    new '{font=[gui.fontawesome]}{/font} Versión antigua'
    old "{font=[gui.fontawesome]}{/font} Authors"
    new "{font=[gui.fontawesome]}{/font} Autores"
    old "{font=[gui.fontawesome]}{/font} Photographers"
    new "{font=[gui.fontawesome]}{/font} Fotógrafos"
    old "{font=[gui.fontawesome]}{/font} Contributors"
    new "{font=[gui.fontawesome]}{/font} Contribuyente"
    old "{font=[gui.fontawesome]}{/font} Rooters"
    new "{font=[gui.fontawesome]}{/font} Hincha"
    old '{font=[gui.fontawesome]}{/font} Special Thanks To'
    new '{font=[gui.fontawesome]}{/font} Agradecimientos especiales a'
    old "ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong, Hoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin, Jeong Yoonsoo, Jianmin Zhang,\nKarina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong, Kim Jeongwoong, Kim Myeongwook,\nLee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins, Lim Jisoo, Maddy Wootton,\nMarshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net"
    new "ACOC, Aiman Sharul, Axel Mertes, Bgame, Brandon Tanimoto, Brian Connors, BRISAK Kim Doohyeon, cheif.choi, Choi Irang, Choi Jihye, cloture, Danielle Bell, Edward N Puckering, Gary King, Gwak Jaeryeol, Han Ihyeong,\nHoe Namyoon, Hong Eunki, Hwang Daehoon, Hyojoon, James Emmerson, Jeong Dongwon, Jeong Wookjin,\nJeong Yoonsoo, Jianmin Zhang, Karina Schulze, Keira Val\'Azr, Kim Hanseol, Kim Hyeoncheol, Kim Jaeseong,\nKim Jeongwoong, Kim Myeongwook, Lee Changki, Lee Eunji, Lee Gunhae, Lee Hyejin, Lee Jaewi, Light Twins,\nLim Jisoo, Maddy Wootton, Marshall Proudfoot, Mirumu, Mojaeng, Oh Hyeonjun, Park Hyeonjun, Park JoonKoo, Rewind, Sander Tieleman, srwss, Sung Chanaul, YottaCho, Zerial.net"
    old "Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King, Peter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon"
    new "Caz Woolley, Game Dev Robot, Gamsadev, Indie GameDev Bot, Indie Game Lover, Indie Games Devel, IndieVideoGames, Joachim Dimitri Jensen, Kim Kyeongtae, Kim Younghwan, Kurt Simon, Linda Lee King,\nPeter Christiansen, Sakimichi, Sebastian Haba, Spero Mcgee, The Indie Sloth, Vrachos, Xin Liu, Yu Shinhyeon"
    old "{font=[gui.fontawesome]}{/font} The information is unknown at this time."
    new "{font=[gui.fontawesome]}{/font} La información es desconocida en este momento."
    old "{b}Birth:{/b} April 19th, 1986"
    new "{b}Nacimiento:{/b} 19 de abril de 1986"
    old "{b}Blood Type:{/b} A(RH+)"
    new "{b}Grupo sanguíneo:{/b} A(RH +)"
    old "{b}Height / Weight:{/b} 165cm / 48kg"
    new "{b}Altura / Peso:{/b} 165cm / 48kg"
    old "{b}BWH:{/b} 81cm / 58cm / 86cm"
    new "{b}PCC:{/b} 81cm / 58cm / 86cm"
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of Yonsei University"
    new "{b}Biografía:{/b} Trabajador desalentado, retiro temporal de la Administración de Salud de la Universidad de Yonsei"
    old "{b}Bio:{/b} Discouraged worker, Temporary absence from Health Administration of ○○ University"
    new "{b}Biografía:{/b} Trabajador desalentado, retiro temporal de la Administración de Salud de la Universidad de OO"
    old "{b}Certificates:{/b} 1st class Hospital Coordinator, Hospital Administrator"
    new "{b}Títulos:{/b} Coordinador de Hospitales de 1ª clase, Administrador de Hospitales"
    old "{b}Likes:{/b} Bagels, Margherita pizza, Sweet rice bun"
    new "{b}Le gusta:{/b} Bagels, pizza Margarita, bollo de arroz dulce"
    old "{b}Dislikes:{/b} Capitalism, Doctors, Members of Parliament"
    new "{b}No le gusta:{/b} Capitalismo, doctores, miembros del parlamento"
    old "{b}Birth:{/b} June 17th, 1989"
    new "{b}Nacimiento:{/b} 17 de junio de 1989"
    old "{b}Blood Type:{/b} O(RH+)"
    new "{b}Grupo sanguíneo:{/b} O(RH +)"
    old "{b}Height / Weight:{/b} 168cm / 48kg"
    new "{b}Altura / Peso:{/b} 168cm / 48kg"
    old "{b}BWH:{/b} 92.5cm / 66cm / 92cm"
    new "{b}PCC:{/b} 92.5cm / 66cm / 92cm"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of Korea Hotel Technical College"
    new "{b}Biografía:{/b} Acompañante de Karaoke, Graduada en Turismo de Alimentos y Bebidas en el Corea Hotel Technical College"
    old "{b}Bio:{/b} Karaoke helper, Graduated in Tourism Food & Beverage of ○○"
    new "{b}Biografía:{/b} Acompañante de Karaoke, Graduada en Turismo de Alimentos y Bebidas en el OO"
    old "{b}Certificates:{/b} 2nd class Barista"
    new "{b}Títulos:{/b} 2ª clase Barista"
    old "{b}Likes:{/b} Money, Photography, Ga-yeon, Drinking"
    new "{b}Le gusta:{/b} Dinero, Fotografía, Ga-yeon, Beber"
    old "{b}Dislikes:{/b} Oryide, Sweet rice bun, Nightclub"
    new "{b}No le gusta:{/b} Oryide, Pan de Arroz dulce, Clubes Nocturnos"
    old "{b}Birth:{/b} December 7th, 1986"
    new "{b}Nacimiento:{/b} 7 de diciembre de 1986"
    old "{b}Died:{/b} October 3rd, 2006"
    new "{b}Deceso:{/b} 3 de octubre de 2006"
    old "{b}Height / Weight:{/b} 158cm / 55kg"
    new "{b}Altura / Peso:{/b} 158cm / 55kg"
    old "{b}BWH:{/b} 89cm / 68.5cm / 85cm"
    new "{b}PCC:{/b} los 89cm / los 68.5cm / los 85cm"
    old "{b}Bio:{/b} Maid of Lauah"
    new "{b}Biografía:{/b} Maid of Lauah"
    old "{b}Certificates:{/b} Craftsman Piano Tuner"
    new "{b}Títulos:{/b} Artesano Afinador de Piano"
    old "{b}Likes:{/b} Ga-yeon, Herself, Papa, Taejin"
    new "{b}Le gusta:{/b} Ga-yeon, Ella misma, Papa, Taejin"
    old "{b}Dislikes:{/b} Kelial, Mother, Tobacco, Truck"
    new "{b}No le gusta:{/b} Kelial, Madre, Tabaco, Camiones"
    old "{b}Staff{/b}"
    new "{b}Personal{/b}"
    old "{b}Clerk{/b}"
    new "{b}Empleada{/b}"
    old "{b}Birth:{/b} April 28th, 1974"
    new "{b}Nacimiento:{/b} 28 de abril de 1974"
    old "{b}Height / Weight:{/b} 168cm / 47kg"
    new "{b}Altura / Peso:{/b} 168cm / 47kg"
    old "{b}BWH:{/b} 90cm / 63.8cm / 89cm"
    new "{b}PCC:{/b} 90cm / 63.8cm / 89cm"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise, Essayist, Graduated in SNU Business School"
    new "{b}Biografía:{/b} Encargado de la Gestión de Empresas en las franquicias de Restaurante Arno, Ensayista, Graduado de SNU Business School"
    old "{b}Bio:{/b} Conductor of Business Management in Arno Restaurant franchise"
    new "{b}Biografía:{/b} Encargado de la Gestión de Empresas en las franquicias de Restaurante Arno"
    old "{b}Certificates:{/b} Doctor of Business Administration, Advanced level of TEPS, Special level of TESAT, Top level of MK TEST"
    new "{b}Títulos:{/b} Doctor en Administración de Empresas, Nivel avanzado de TEPS, Nivel especial de TESAT, Nivel superior de MK TEST"
    old "{b}Likes:{/b} Acoustic guitar, Challenge, Taejin, Writing"
    new "{b}Le gusta:{/b} Guitarra acústica, Desafío, Taejin, Escritura"
    old "{b}Dislikes:{/b} Electronic products, Game, Mantis, Sloth"
    new "{b}No le gusta:{/b} Productos electrónicos, Juego, Mantis, Perezosos"
    old "{b}Interviewer{/b}"
    new "{b}Entrevistador{/b}"
    old "{b}Birth:{/b} Top Secret"
    new "{b}Nacimiento:{/b} Ultra secreto"
    old "{b}Height / Weight:{/b} Top Secret"
    new "{b}Altura / Peso:{/b} Ultra secreto"
    old "{b}BWH:{/b} Top Secret"
    new "{b}PCC:{/b} Ultra secreto"
    old "{b}Bio:{/b} Conductor of Business Management in ○○"
    new "{b}Biografía:{/b} Encargado de la Gestión de Empresas en las franquicias de OO"
    old "{b}Birth:{/b} January 19th, 1986"
    new "{b}Nacimiento:{/b} 19 de enero de 1986"
    old "{b}Blood Type:{/b} AB(RH+)"
    new "{b}Grupo sanguíneo:{/b} AB (RH +)"
    old "{b}Height / Weight:{/b} 172cm / 58kg"
    new "{b}Altura / Peso:{/b} 172cm / 58kg"
    old "{b}Bio:{/b} Bassist of The Ghost Crying"
    new "{b}Biografía:{/b} Bajista de The Ghost Crying"
    old "{b}Bio:{/b} Bassist of ○○"
    new "{b}Biografía:{/b} Bajista de OO"
    old "{b}Likes:{/b} Bob Dylan, Choi Ga-yeon, Yu Jaeha"
    new "{b}Le gusta:{/b} Bob Dylan, Choi Ga-yeon, Yu Jaeha"
    old "{b}Dislikes:{/b} Auditions, Management, Soju"
    new "{b}No le gusta:{/b} Audiciones, Gestión, Soju"
    old "{b}Birth:{/b} March 28th, 1986"
    new "{b}Nacimiento:{/b} 28 de marzo de 1986"
    old "{b}Blood Type:{/b} B(RH+)"
    new "{b}Grupo sanguíneo:{/b} B (RH +)"
    old "{b}Height / Weight:{/b} 182cm / 73kg"
    new "{b}Altura / Peso:{/b} 182cm / 73kg"
    old "{b}Bio:{/b} Lead Guitarist of The Ghost Crying, Graduated in Seoul Institute of the Arts"
    new "{b}Biografía:{/b} Guitarrista principal de The Ghost Crying, graduado en el Instituto de Artes de Seúl"
    old "{b}Bio:{/b} Lead Guitarist of ○○, Graduated in ○○"
    new "{b}Biografía:{/b} Guitarrista principal de OO, graduado en el Instituto de OO"
    old "{b}Certificates:{/b} Bachelor of Arts Degree in Gebrauchsmusik"
    new "{b}Títulos:{/b} Licenciatura en Usos de la Musica"
    old "{b}Likes:{/b} Marylin Manson, NIN, Rammstein, Shin Junghyeon,\nShin Haechul"
    new "{b}Le gusta:{/b} Marylin Manson, NIN, Rammstein, Shin Junghyeon, Shin Haechul"
    old "{b}Dislikes:{/b} Eggplant, Ginger, Idol"
    new "{b}No le gusta:{/b} Berenjena, jengibre, los Idols"
    old "{b}Birth:{/b} December 17th, 1979"
    new "{b}Nacimiento:{/b} 17 de diciembre de 1979"
    old "{b}Bio:{/b} Physician, Graduated in School of Medicine of Sungkyunkwan University"
    new "{b}Biografía:{/b} Médico, Graduado en la Facultad de Medicina de la Universidad de Sungkyunkwan"
    old "{b}Bio:{/b} Physician, Graduated in ○○"
    new "{b}Biografía:{/b} Médico, Graduado en la Facultad de Medicina de la Universidad de OO"
    old "{b}Certificates:{/b} Medical Licence"
    new "{b}Títulos:{/b} Licencia Médica"
    old "{b}Likes:{/b} Fame, Money, Power"
    new "{b}Le gusta:{/b} Fama, Dinero, Poder"
    old "{b}Dislikes:{/b} Capitalism, Members of Parliament, Soju"
    new "{b}No le gusta:{/b} Capitalismo, Miembros del Parlamento, Soju"
    old "{b}Bio:{/b} Physician"
    new "{b}Biografía:{/b} Médico"
    old "{font=[gui.fontawesome]}{/font} Stop"
    new "{font=[gui.fontawesome]}{/font} Detener"
    old "{font=[gui.fontawesome]}{/font} Shuffle"
    new "{font=[gui.fontawesome]}{/font} Barajar"
    old "{font=[gui.fontawesome]}{/font} Loop"
    new "{font=[gui.fontawesome]}{/font} Lazo"
    old "{font=[gui.fontawesome]}{/font} Previous"
    new "{font=[gui.fontawesome]}{/font} Anterior"
    old "{font=[gui.fontawesome]}{/font} Next"
    new "{font=[gui.fontawesome]}{/font} Siguiente"
    old "{font=[gui.fontawesome]}{/font} Random"
    new "{font=[gui.fontawesome]}{/font} Aleatorio"
    old "{font=[gui.fontawesome]}{/font} Add to cart"
    new "{font=[gui.fontawesome]}{/font} Añadir a la cesta"
    old '{size=[gui.quick_button_text_size]}Stop{/size}'
    new '{size=[gui.quick_button_text_size]}Detener{/size}'
    old '{size=[gui.quick_button_text_size]}Previous{/size}'
    new '{size=[gui.quick_button_text_size]}Anterior{/size}'
    old '{size=[gui.quick_button_text_size]}Next{/size}'
    new '{size=[gui.quick_button_text_size]}Siguiente{/size}'
    old '{size=[gui.quick_button_text_size]}Loop{/size}'
    new '{size=[gui.quick_button_text_size]}Lazo{/size}'
    old '{size=[gui.quick_button_text_size]}Shuffle{/size}'
    new '{size=[gui.quick_button_text_size]}Barajar{/size}'
    old "Prologue"
    new "Prólogo"
    old "Discouraged Worker"
    new "Trabajador desalentado"
    old "Depressive Disorder"
    new "Desorden depresivo"
    old "Reclusive Outsider"
    new "Reacio a Salir"
    old "IMF Crisis"
    new "Crisis del FMI"
    old "Anxiety Disorder"
    new "Trastorno de ansiedad"
    old "Medical Referral"
    new "Referencia médica"
    old "Bridge of the Life"
    new "Puente de la Vida"
    old "Epilogue"
    new "Epílogo"
    old "Accident"
    new "Accidente"
    old "Flowery Mornings and Moonlit Nights"
    new "Mañanas floridas y noches iluminadas por la luna"
    old "Red Dialogue Window"
    new "Ventana de diálogo rojo"
    old "Seohae Grand Bridge"
    new "Coalición en Seohae Bridge"
    old " A discouraged worker is a person of legal employment age who is not actively seeking employment, or who can not find employment after long-term unemployment. This is usually because an individual has given up looking or has had no success in finding a job, hence the term \"discouraged\".\n\n{a=https://en.wikipedia.org/wiki/Discouraged_worker}Wikipedia{/a}\n\n Discouraged workers are classified as an economically inactive population and not included in the unemployment rate, although they are actually unemployed.\n\n And this artificially causes a decrease in the unemployment rate in official statistics, in spite of an actually higher unemployment rate. In the case of Korea, the Subsidiary Employment Index, which includes the not-calculated unemployed, was reported first in November, 2014, and accordingly, the hidden problems in Korea's employment-population ratio and discouraged workers have surfaced."
    new " Un trabajador desalentado es una persona en edad legal de trabajar que no está buscando empleo activamente, o que no puede encontrar empleo después de un desempleo de larga duración. Esto suele ser porque un individuo ha renunciado a buscar o no ha tenido éxito en encontrar un trabajo, de ahí el término \"desalentado\".\n\n Los trabajadores desalentados son clasificados como una población económicamente inactiva y no están incluidos en la tasa de desempleo, aunque en realidad están desempleados.\n\n Y esto provoca artificialmente una disminución de la tasa de desempleo en las estadísticas oficiales, a pesar de una tasa de desempleo realmente más alta. En el caso de Corea, el Índice de Empleo Subsidiario, que incluye a los desempleados no calculados, se informó primero en noviembre de 2014 y, por consiguiente, han surgido los problemas ocultos en la relación empleo-población de Corea y trabajadores desalentados."
    old " Reclusive outsider is the phenomenon of reclusive adolescents or adults who withdraw from social life, often seeking extreme degrees of isolation and confinement. The term reclusive outsider refers to both the sociological phenomenon in general as well as to people belonging to this societal group.\n\n{a=https://en.wikipedia.org/wiki/Hikikomori}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover.\n\n In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " Reacio a salir es el fenómeno de adolescentes reclusos o adultos que se retiran de la vida social, a menudo buscando grados extremos de aislamiento y confinamiento. El término se refiere tanto al fenómeno sociológico en general como a las personas pertenecientes a este grupo social.\n\n Choi Ga-yeon, una heroína de \"Trabajadores Desalentados\", sufría de trastorno depresivo debido al repentino despido de su trabajo y la ruptura con su amante.\n\n Además, con su continuo fracaso en conseguir un trabajo, sus síntomas de trastorno de ansiedad sólo empeoraron. Y ella naturalmente se ha convertido en un hikikomori (una persona que se convierte en un recluso y renuncia a cualquier vida social) después de que renunció a tratar de conseguir un trabajo."
    old " Generally, a medical referral is issued by a hospital when sending a patient to another hospital. Ga-yeon has received medical treatment from a psychiatrist since she was fired from the hospital where she was working as a coordinator. In spite of long treatment, her condition did not improve at all, and the hospital issued a medical referral to another hospital. But Ga-yeon refused the referral as she felt the psychiatrist gave up on her, and this made her fall into despair. So she didn't seek any more psychiatric treatment.\n\n Since many people still think negatively about seeking psychiatric treatment, and have unfavorable perceptions about those who seek it, often, people who need help with their problems, tend to avoid getting the help they need, both here in Korea and elsewhere in the world.\n\n Also in the case of Ga-yeon, she hasn't talked about it, regarding it as her embarrassing secret. The medical referral Yunwoo found in Ga-yeon's mailbox was actually a referral that Hye-na arranged for her.\n\n Actually, the description shown in the medical referral in the \"Ga-yeon and Yunwoo\" part of the story, is almost the same as the one commonly issued in a real hospital in Korea."
    new " Generalmente, un hospital envía una remisión médica cuando envía a un paciente a otro hospital. Ga-yeon ha recibido tratamiento médico de un psiquiatra desde que fue despedida del hospital donde trabajaba como coordinadora. A pesar del largo tratamiento, su estado no mejoró en absoluto, y el hospital emitió una remisión médica a otro hospital. Pero Ga-yeon rechazó la remisión al sentir que el psiquiatra se rindió a ella, y esto la hizo caer en la desesperación. Así que no buscó más tratamiento psiquiátrico.\n\n Dado que muchas personas todavía piensan negativamente acerca de la búsqueda de tratamiento psiquiátrico, y tienen percepciones desfavorables acerca de quienes lo buscan, a menudo, las personas que necesitan ayuda con sus problemas, tienden a evitar la ayuda que necesitan, tanto aquí en Corea y en otras partes del mundo.\n\n También en el caso de Ga-yeon, ella no ha hablado de ello, considerándolo como su secreto embarazoso. La Referencia médica que Yunwoo encontró en el buzón de Ga-yeon era en realidad una remisión que Hye-na arregló para ella.\n\n En realidad, la descripción que se muestra en la referencia médica en la parte \"Ga-yeon y Yunwoo\" de la historia, es casi la misma que la comúnmente emitida en un hospital real en Corea."
    old " Anxiety disorders are a category of mental disorders characterized by feelings of anxiety and fear, where anxiety is a worry about future events and fear is a reaction to current events. These feelings may cause physical symptoms, such as a racing heart and shakiness.\n\n{a=https://en.wikipedia.org/wiki/Anxiety_disorder}Wikipedia{/a}\n\n My mother had suffered from panic disorder for almost eight years, and she used to complain of pain and hyperpnea in certain and sometimes new and unexpected situations(Hyperpnea is the need to breathe more deeply because the person experiencing it feels light headed or otherwise feels they need more oxygen for various reasons.).\n\n And someone whom I know had anxiety disorder, and she suffered from a tic disorder including repetitive eye blinking and apnea when she feels anxiety in those same kinds of situations. She was even very dependent on alcohol and showed symptoms of caffeine addiction as well. Standing by my mother's and her side, and watching their pain and experiencing it with them, I hoped to help set them free from those painful days. But as time went by, I found I was getting numb with their pain, and at that moment, I felt extremely ashamed as a human being."
    new " Los trastornos de ansiedad son una categoría de trastornos mentales caracterizados por sentimientos de ansiedad y miedo, donde la ansiedad es una preocupación acerca de los eventos futuros y el miedo es una reacción a los acontecimientos actuales. Estos sentimientos pueden causar síntomas físicos, como taquicardia (Aumento del ritmo cardiaco) y temblores.\n\n Mi madre había sufrido de trastorno de pánico durante casi ocho años, y solía quejarse de dolor e hiperpnea en ciertas situaciones ya veces nuevas e inesperadas (la hiperpnea es la necesidad de respirar más profundamente porque la persona que experimenta se siente ligero o siente de otra manera Necesitan más oxígeno por varias razones).\n\n Y alguien a quien conozco tenía trastorno de ansiedad, y sufría de un trastorno de tics incluyendo parpadeo repetitivo de ojos y apnea cuando se siente ansiedad en los mismos tipos de situaciones. Ella era incluso muy dependiente del alcohol y mostró síntomas de la adicción a la cafeína también. De pie junto a mi madre y de su lado, y viendo su dolor y experimentando con ellos, esperaba ayudar a liberarlos de esos días dolorosos. Pero a medida que pasaba el tiempo, me di cuenta de que me estaba adormeciendo con su dolor, y en ese momento, me sentí muy avergonzado como un ser humano."
    old " Depressive disorder is a mental disorder characterized by a pervasive and persistent low mood that is accompanied by low self-esteem and by a loss of interest or pleasure in normally enjoyable activities. The term \"depression\" is used in a number of different ways. It is often used to mean this syndrome but may refer to other mood disorders or simply to a low mood. Major depressive disorder is a disabling condition that adversely affects a person's family, work or school life, sleeping and eating habits, and general health.\n\n{a=https://en.wikipedia.org/wiki/Major_depressive_disorder}Wikipedia{/a}\n\n Choi Ga-yeon, a heroine of \"Discouraged Workers\", suffered from depressive disorder because of the sudden firing from her job and breaking-up with her lover. In addition, with her continuous failure to get a job, her anxiety disorder symptoms only became worse. And she naturally has become a hikikomori(a person who becomes a recluse and gives up any social life) after she gave up trying to get a job."
    new " El trastorno depresivo es un trastorno mental caracterizado por un estado de ánimo omnipresente y persistente que se acompaña de baja autoestima y de una pérdida de interés o placer en actividades normalmente agradables. El término \"depresión\" se usa de varias maneras diferentes. A menudo se utiliza para significar este síndrome, pero puede referirse a otros trastornos del estado de ánimo o simplemente a un estado de ánimo bajo. El trastorno depresivo mayor es una condición incapacitante que afecta negativamente la vida familiar, laboral o escolar de una persona, los hábitos de dormir y comer y la salud en general.\n\n Choi Ga-yeon, una heroína de \"Trabajadores Desalentados\", sufría de trastorno depresivo debido al repentino despido de su trabajo y la ruptura con su amante.\n\n Además, con su continuo fracaso en conseguir un trabajo, sus síntomas de trastorno de ansiedad sólo empeoraron. Y ella naturalmente se ha convertido en un hikikomori (una persona que se convierte en un recluso y renuncia a cualquier vida social) después de que renunció a tratar de conseguir un trabajo."
    old " \"Bridge of the life\" was actually a sort of attempt using advanced technological methods to prevent suicide. By trying to have a conversation with a pedestrian through hopeful words and changing their desperation into hope, the designers thought suicidal people might be encouraged not to end their lives, but, in the event that failed, there was still the traditional physical anti-suicide barrier. The sensors mounted on every section of the bridge detects the exact location of a pedestrian as she/he walks by and the bridge lights the hopeful word up in the right position for a pedestrian to read.\n\n The very first bridge of life opened on Mapo Bridge, Korea on September 26, 2012, and was sponsored by Seoul City and Samsung Life Insurance. Mapo Bridge was chosen as the first installation of this new technology because it has been notorious as the place with the highest suicide rate. And the second one opened on Hangang Bridge, Korea on November 5, 2013, sponsored by Korea Health Promotional Foundation.\n\n And the ad for \"Bridge of the life\" received 39 awards in the International Advertising Festival and obtained excellent advertising effects. But regardless of this successful record, the rate of suicides by death leap has steadily increased. According to statistics, installing closed circuit television on the public bridges was more helpful in preventing suicide jumps and rescuing suicide jumpers who actually did jump than the bridge of life technology.\n\n As a result of the Samsung Life Insurance's decision to discontinue their operational support for \"Bridge of the Life\" on Mapo Bridge in September 2015, the automatic detection sensor has not worked since December 1, 2015 and the website of Bridge of the Life was also closed.\n\n In fact, Hangang Bridge wasn't yet built at the time that the \"Discouraged workers\" story takes place. But in the game, it was set as a background to let Yunwoo try to think where Ga-yeon disappeared to."
    new " \"Puente de la vida\" era en realidad una especie de intento de utilizar métodos tecnológicos avanzados para prevenir el suicidio. Al tratar de tener una conversación con un peatón a través de palabras de esperanza y el cambio de su desesperación en esperanza, los diseñadores pensaron que los suicidas podrían ser alentados para no terminar sus vidas, pero, en el caso de que no, todavía existía la tradicional barrera física anti-suicidio. Los sensores montados en cada sección del puente detecta la ubicación exacta de un peatón mientras ella / él camina y el puente ilumina las palabras de esperanza en la posición correcta para que un peatón para leer.\n\n El primer puente de la vida se abrió en el Bridge Mapo, Corea el 26 de septiembre de 2012, y fue patrocinado por la ciudad de Seúl y Samsung Life Seguros. Mapo fue elegido como el primer lugar para la instalación de esta nueva tecnología, ya que ha sido notorio que tiene la tasa de suicidios más alta, y el segundo se instaló en Hangang Bridge, Corea el 5 de noviembre de 2013, patrocinado por Korea Health Promotional Foundation.\n\n Según las estadísticas, la instalación de circuito cerrado de televisión (Puente de la vida) recibió 39 premios en el Festival Internacional de Publicidad y adquirió excelentes efectos publicitarios. En los puentes públicos fue más útil en la prevención de suicidios y en el rescate de suicidas que realmente saltaron del puente con esta tecnología de apoyo.\n\n Como resultado de la decisión del Samsung Life Insurance de  interrumpir su apoyo operativo para \"Puente de la Vida\" en Bridge Mapo en septiembre de 2015, el sensor de detección automática no ha funcionado desde el 1 de diciembre, 2015, y el sitio web del puente de la vida también fue cerrado.\n\n De hecho, el Bridge Hangang aún no se había construido en el momento en el que la historia de \"Trabajadores desanimados\" tiene lugar. Pero en el juego, se establece como un fondo para que Yunwoo piense en donde puede estar Ga-yeon."
    old " The Asian financial crisis was a period of financial crisis that gripped much of East Asia beginning in July 1997 and raised fears of a worldwide economic meltdown due to financial contagion.\n\n The crisis started in Thailand with the financial collapse of the Thai baht after the Thai government was forced to float the baht due to lack of foreign currency to support its fixed exchange rate, cutting its peg to the U.S. dollar, after exhaustive efforts to support it in the face of a severe financial over-extension that was in part real estate driven.\n\n{a=https://en.wikipedia.org/wiki/1997_Asian_financial_crisis#South_Korea}Wikipedia{/a}\n\n At the time, Thailand had acquired a burden of foreign debt that made the country effectively bankrupt even before the collapse of its currency. As the crisis spread, most of Southeast Asia and Japan saw slumping currencies, devalued stock markets and other asset prices, and a precipitous rise in private debt.\n\n Indonesia, South Korea and Thailand were the countries most affected by the crisis. Hong Kong, Laos, Malaysia and the Philippines were also hurt by the slump. Brunei, China, Singapore, Taiwan and Vietnam were less affected, although all suffered from a loss of demand and confidence throughout the region."
    new " La crisis financiera asiática fue un período de crisis financiera que afectó gran parte de Asia Oriental a partir de julio de 1997, y aumentó los temores de una crisis económica a nivel mundial debido al contagio financiero.\n\n Reducir su paridad con el dólar estadounidense, después de exhaustivos esfuerzos para apoyarla en la cara de una severa sobre-extensión financiera que fue en parte impulsada por bienes raíces.\n\n A medida que la crisis se extendía, la mayor parte del sureste asiático y Japón vieron caídas de divisas, mercados de valores devaluados y otros precios de activos, y un aumento precipitado de la deuda privada.\n\n Brunei, China, Singapur, Taiwán y Vietnam fueron menos afectados, pero todos sufrieron pérdidas (Hong Kong, Laos, Malasia y Filipinas) por las demandas y la confianza en toda la región."
    old " \"Accident\" tells what happens after \"Epilogue\" which is the basic ending of \"Discouraged Workers\".\n\n Ga-yeon reached out her hand toward Yunwoo, but at that moment, she blacked out and fell off the bridge. And Yunwoo threw himself into the river to save her. A few days later, they rose to the surface, and one passerby's report told their deaths to the world.\n\n If Yunwoo hadn't found his wallet, Ga-yeon would die alone while he was haggling over the taxi fare."
    new " \"Accidente\" cuenta lo que sucede después de \"Epílogo\", que es el final básico de \"Trabajadores Desalentados\".\n\n Yunwoo se arrojó al río para salvarla, y pocos días más tarde son encontrados sus cuerpos, y el informe de un transeúnte cuenta sus muertes al mundo.\n\n Si Yunwoo no hubiera encontrado su billetera, Ga-yeon moriría sola mientras regateaba por el precio del taxi."
    old " As a hospital coordinator, Ga-yeon fell in love with a doctor at the hospital she was working in and they had an affair even though the doctor was a married man. When the director found out, she was fired. For over a year she tried to find another job, but her mental uneasiness eventually made her give up and she became a recluse.\n\n A year later, in the spring of 2013, her younger sister, Hye-na, and her first love Yunwoo come to her.\n\n A story about the dark side of today's youth and serious life events happening around Ga-yeon."
    new " As a hospital coordinator, Ga-yeon fell in love with a doctor at the hospital she was working in and they had an affair even though the doctor was a married man. When the director found out, she was fired. For over a year she tried to find another job, but her mental uneasiness eventually made her give up and she became a recluse.\n\n A year later, in the spring of 2013, her younger sister, Hye-na, and her first love Yunwoo come to her.\n\n A story about the dark side of today's youth and serious life events happening around Ga-yeon."
    old " \"Flowery Mornings and Moonlit Nights\" is the true ending which assumes that Ga-yeon didn't faint and grabbed Yunwoo's hand in \"Epilogue\". Originally \"Discouraged Workers\" was intended to end with the \"Accident\" story as the true ending. But after deciding to release it in the market, this was chosen as the true ending.\n\n Ga-yeon finds the culprit who spread the video, with the help of Yunwoo, and reports him to the police. After that, she tries to find a job, but it's still not easy for her. Even some interviewers who know her, hurt her.\n\n Yunwoo just stays by her side and tries to protect her without saying anything, and Hye-na helps Ga-yeon to work part-time at the cafe where she's working. Ga-yeon works hard every day, grateful for being allowed to work there. One day, the cafe manager gives her a letter of recommendation from the general manager of the head office, and Ga-yeon gets an opportunity to have an interview for a large affiliated store run by the head office. And by chance, the interviewer she meets with for the job is her old boss, who during her schooldays, originally gave her the idea of her dream job being a restaurant manager. Ga-yeon passes the interview with ease, and finally, she starts to move towards her dream."
    new " \"Florido mañanas y las iluminadas por la luna Noches\" es el verdadero final que supone que Ga-yeon no se desmayó y agarró la mano de Yunwoo en \"Epílogo\". Originalmente \"Trabajadores desanimados\" tenía la intención de terminar con la historia \"accidente\" como el verdadero final. Pero después de decidir lanzarlo en el mercado, éste fue elegido como el final verdadero.\n\n Ga-yeon encuentra el culpable que difundió el video, con la ayuda de Yunwoo, y le informa a la policía. Después de eso, se trata de encontrar un trabajo, pero aun así no es fácil para ella. Incluso hay algunos entrevistadores que la conocen, ella se lamenta por esto.\n\n Yunwoo sólo se queda a su lado y trata de protegerla, sin decir nada, y Hye-na ayuda Ga-yeon para trabajar a tiempo parcial en el café donde ella está trabajando. Ga-yeon trabaja duro todos los días, agradecido porque se les permita trabajar allí. Un día, el gestor de café le da una carta de recomendación del director general de la oficina central, y Ga-yeon tiene la oportunidad de tener una entrevista para una gran tienda afiliada a cargo de la oficina central. Y por casualidad, el entrevistador Ga-yeon pasa la entrevista con facilidad, y finalmente, comienza a moverse hacia su sueño."
    old " A chain reaction collision, involving 29 vehicles, happened at 7:50am on October 3, 2006, Korean time, on Seohae Grand Bridge in South Korea. This collision happened due to a thick fog, and it left 12 people dead and about 50 injured. According to the investigation, the accident occurred not only because of bad weather, but also because some drivers were speeding as well as shoulder riding. But whatever the reason was, the damage was almost 4 billion won, which was the most awful and costly accident in Korean car insurance history.\n\n \"Lee Seol-ah\" is a fictitious character who died in this accident. This woman, who died at the age of 21, still in the flower of her youth, visits the world she used to live in after she died, and watches people whom she loved and shared friendships with. One day, she meets Ga-yeon who helped her in the past. To prevent her death, she decides to help Yunwoo."
    new " Esta colisión se produjo debido a una niebla espesa, y dejó 12 muertos y cerca de 50 heridos Pero sea cual fuere la razón, el daño fue casi 4 mil millones de won, que fue el más terrible y costoso accidente en la historia del seguro de coches de Corea.\n\n \"Lee Seol-ah\" es un personaje ficticio que murió en este accidente. Esta mujer, que murió a la edad de 21 años, todavía en la flor de su juventud, visita el mundo en el que vivía en después de su muerte, y mira la gente Un día reconoce a Ga-yeon que la ayudó en el pasado, para evitar su muerte decide ayudar a Yunwoo."
    old " In \"Discouraged Workers\", a word box in red color is used to show the words and thoughts of Ga-yeon and a clerk Because when the basic scenario was developed, they are actually not alive.\n\n But when Ga-yeon is talking with her mom on the phone, the black box is used out of consideration for her mother."
    new " En \"Trabajadores desalentados\", un cuadro de palabra en color rojo se utiliza para mostrar las palabras y los pensamientos de Ga-yeon y un empleado porque cuando se desarrolla la trama en el escenario, en realidad no están vivos.\n\n Pero cuando Ga-yeon está hablando con su mamá por teléfono, la caja negra se usa por consideración de su madre."
    old "{font=[gui.fontawesome]}{/font} Find the diary in the room."
    new "{font=[gui.fontawesome]}{/font} Find the diary in the room."
    old "My cool captain!"
    new "¡Mi grandiosa Capitán!"
    old "My captain's tear"
    new "Las lágrimas de mi Capitán"
    old "Went to see Yunwoo"
    new "Fuimos a ver Yunwoo"
    old "I rejected him"
    new "Lo rechacé"
    old "As a friend"
    new "Como amigo"
    old "My days in hospital"
    new "Mis días en el hospital"
    old "Observing a doctor"
    new "Observar a un médico"
    old "His wife"
    new "Su esposa"
    old "Farewell"
    new "Despedida"
    old "I miss him"
    new "Le extraño"
    old "Sign"
    new "Síntomas"
    old "A lunatic"
    new "Un loco"
    old "My friend, Eunju"
    new "Mi amigo, Eunju"
    old "Getting a job"
    new "Conseguir un trabajo"
    old "Rubbish and rubbish can"
    new "Basura y Basurero"
    old "Dying message"
    new "Mensaje moribundo"
    old " It's been more than a month since I started working in a family restaurant. In the beginning, it was really hard to carry a tray and I even broke a few dishes. But now, I feel like I'm getting better and better. Sometimes, customers tip me as well, and also the other staff often praises my work. I'm especially good at…. hmmm…. well, it's too many to write them all down here! Later!\n\n However, the captain looks really cool. She's beautiful, smart, and also good at her work. Oh, she seems to be strong as well, as she usually carries heavy things by herself!\n\n I saw her carrying two metal trays stacked with dishes with just her two hands. It is hard even for men, but she's such a superwoman. How the hell can she do that? I hope I can do work as well as her someday."
    new " Ha pasado más de un mes desde que empecé a trabajar en un restaurante familiar. Al principio, era muy difícil llevar una bandeja e incluso rompí algunos platos. Pero ahora, siento que estoy mejorando. A veces, los clientes me propina también, y también el otro personal elogia a menudo mi trabajo. Soy especialmente buena en.... hmmm bueno, son demasiadas cosas para escribirlas todas aquí! ¡Luego!\n\n Sin embargo, la Capitán se ve muy bien. Ella es hermosa, inteligente, y también buena en su trabajo. ¡Oh, parece ser fuerte también, ya que por lo general lleva cosas pesadas por sí misma!\n\n La vi cargando dos bandejas de metal con platos apilados con sólo sus dos manos. Es duro incluso para los hombres, pero ella es una Supermujer. ¿Cómo diablos puede hacer eso? Espero poder trabajar tanto como ella algún día."
    old " Today the section chief of the head office visited the restaurant. I thought the chief would be a man, but she was a young woman. She came to our restaurant and called the captain to the locker room. She passed by me while I was working there, and I saw her nametag. And I found she has the same name as a famous comedian. Funny!\n\n As the captain was not in the hall, I tried to look for her, and when I opened the door of the locker room, she looked at me in surprise and turned her face hurriedly. And she said leave her alone for a while, forcing me out of the room. She was crying.\n\n Probably the section chief made her cry. That bitch! What did the captain do wrong? Hey, I'll get even with her!! Shit!"
    new " Hoy el jefe de sección de la oficina central visitó el restaurante. Pensé que el jefe sería un hombre, pero era una mujer joven. Ella vino a nuestro restaurante y llamó a la Capitán al vestuario. Pasó junto a mí mientras trabajaba allí, y vi su nombre. Y me di cuenta de que tiene el mismo nombre que un famoso comediante. ¡Gracioso!\n\n Como el gerente no estaba en el pasillo, traté de buscarla, y cuando abrí la puerta del vestuario, ella me miró con sorpresa y volvió su rostro apresuradamente. Y ella dijo que la dejara sola por un tiempo, forzándome a salir de la habitación. Ella estaba llorando.\n\n Probablemente el jefe de sección la hizo llorar. ¡Esa perra! ¿Qué hizo mal la Capitán? ¡Hey, voy a llegar incluso con ella! ¡Mierda!"
    old " I went to Cheolwon, with Eunyoung to see Yunwoo today. I didn't realize it was that cold, but when I got off the bus, I was just shocked as it was literally freezing. It didn't snow, and the wind didn't blow, but cold air made even my eyes freeze. Eunyoung and I hurried into the visitor's room to wait for Yunwoo.\n\n A few minutes later, a soldier came in - actually I recognized that he was Yunwoo as soon as I saw him! And I got the giggles. His camouflage patterned muffler looked pretty cool, but his earmuffs reminded me of a once famous singer, and I couldn't stop laughing!\n\n I told him about that singer, and he got embarrassed. Eunyoung took his earmuffs away and danced, and all of us burst into laughter.\n\n However, since we said goodbye to Yunwoo, I've felt somewhat lonesome, and I still feel that way even as I'm writing this…. why do I feel this way?"
    new " Fui a Cheolwon, con Eunyoung para ver a Yunwoo hoy. No me di cuenta de que hacia tanto frio, pero cuando bajé del autobús, me sorprendió que estuviera literalmente helado. No nevaba, y el viento no soplaba, pero el aire frío hacía que mis ojos se congelaran. Eunyoung y yo nos apresuramos a entrar en sala de espera para esperar a Yunwoo.\n\n Unos minutos más tarde, un soldado entró… ¡De hecho reconocí que era Yunwoo tan pronto como lo vi! Y me dio risa. Su uniforme de camuflaje parecía bastante guay, pero sus orejeras me recordó a una famosa cantante, y no podía dejar de reír!\n\n Le conté acerca de ese cantante, y se avergonzó. Eunyoung se llevó las orejeras y bailó, y todos nos echamos a reír.\n\n Sin embargo, desde que nos despedimos de Yunwoo, me he sentido algo solitaria, y todavía me siento así incluso mientras escribo esto.... ¿Por qué me siento de esta manera?"
    old " After I parted with him, and while I was coming home, I tried really hard to fight back tears. But when I arrived in my room, I just burst into tears. Why? Why was I so mean to him? I raged at him, and told him to quit music. Why the hell did I do that?\n\n Today he told me what I've really looked forward to hearing from him, but why…. why couldn't I accept him? And why did I hurt him? I can't stop crying…."
    new " Después de que me separé con él, y mientras yo volvía a casa, me esforcé mucho para luchar contra las lágrimas. Pero cuando llegué a mi habitación, me eché a llorar. ¿Por qué? ¿Por qué era tan malo para él? Me enojé con él, y le dije que dejara la música. ¿Por qué diablos hice eso?\n\n Hoy me dijo lo que realmente esperaba escuchar de él, pero por qué.... ¿Por qué no podía aceptarlo? ¿Y por qué le hice daño? No puedo dejar de llorar...."
    old " I had a long conversation with Yunwoo today;\n\n You've just been discharged from the army, and I'm a student without a job. So what can we do now? You really think we can get married and start our home? Seriously? How?\n\n Besides, we're not romantically involved with each other. We're just friends. I think of you as my friend, and hope we could get along well with each other for a long time. That's all….\n\n I think I probably said it like that…. but of course it's not true that I think of him just as a friend, but…. To get back to our relationship as usual, I had to say it that way.\n\n I also said sorry that I hurt him.\n\n However, unexpectedly, it seemed he doesn't care about it. He said he was actually kidding when he asked me to marry him. And since I already refused his proposal anyway, there's nothing hard about getting along with me simply as a friend.\n\n What he said made me a little bit regretful, but anyway, we decided to leave as good friends as we've always been."
    new " Hoy tuve una larga conversación con Yunwoo.\n\n Acaba de ser dado de alta del ejército, y soy un estudiante sin trabajo. ¿Entonces, que podemos hacer ahora? ¿De verdad piensas que podemos casarnos y empezar nuestra casa? ¿Seriamente? ¿Cómo?\n\n Además, no estamos románticamente involucrados el uno con el otro. Sólo somos amigos. Pienso en ti como mi amigo, y espero que podamos llevarnos bien el uno con el otro durante mucho tiempo. Eso es todo….\n\n Creo que probablemente lo dije así.... pero por supuesto no es cierto que yo pienso en él como un amigo, pero.... Para volver a nuestra relación como siempre, tuve que decirlo de esa manera.\n\n También dije que lo lastimé.\n\n Sin embargo, inesperadamente, parecía que no le importaba. Dijo que en realidad estaba bromeando cuando me pidió que me casara con él. Y ya que rechacé su propuesta de todos modos, no hay ningún problema para llevarse bien conmigo simplemente como un amigo.\n\n Lo que dijo me hizo un poco lamentable, pero de todos modos, decidimos salir como buenos amigos como siempre hemos sido."
    old " It's been almost a year since I started working in this hospital. I work as a coordinator of the hospital. I had my salary raised, and also I'm pretty satisfied with my job. My savings account with the balance which gets bigger and bigger makes me feel really happy.\n\n When I had to quit the university temporarily, I was just stunned. But now that I think about it, it was rather smart to do that, actually. Because of that choice, I was able to pay Hye-na's university tuition, without a loan.\n\n I'll save more money to send Mom and Daddy to travel on, and also support Hye-na until she gets married someday. Jeez, why is time passing so fast today? Until tomorrow, I'm going to bed!\n\n Ga-yeon, just keep it up as you've done so far!"
    new " Ha pasado casi un año desde que empecé a trabajar en este hospital. Trabajo como coordinador del hospital. Tenía mi sueldo aumentado, y también estoy bastante satisfecha con mi trabajo. Mi cuenta de ahorros se hace más grande y más grande me hace sentir muy feliz.\n\n Cuando tuve que dejar la universidad temporalmente, estaba simplemente aturdida. Pero ahora que lo pienso, fue bastante inteligente hacerlo, en realidad. Debido a esa opción, pude pagar la matrícula universitaria de Hye-na, sin un préstamo.\n\n Voy a ahorrar más dinero para enviar a mamá y papá a viajar, y también apoyar a Hye-na hasta que se casa algún día. Jeez, ¿Por qué el tiempo pasa tan rápido hoy? ¡Hasta mañana, me voy a la cama!\n\n ¡Ga-yeon, sólo mantente como lo ha hecho hasta ahora!"
    old " Oh, my god…. how could he look like him that much? His face, way of talking, character, and even that he can't hold liquor well…. everything is just like him. He reminds me of Yunwoo a lot. And it makes me feel sad. And this keeps bothering me so much. These days, I'm often trying to speak to him, or be around him. He also seems to be interested in me, and sometimes talks to me, or brings some snack or drink. He looks like a pretty good man."
    new " Oh Dios mío…. ¿cómo podía verse tan parecido a él? Su rostro, manera de hablar, carácter, e incluso que él no puede soportar el licor bien.... todo es igual que él. Me recuerda mucho a Yunwoo. Y me hace sentir triste. Y esto sigue molestándome tanto. Estos días, a menudo estoy tratando de hablar con él, o estar a su alrededor. También parece estar interesado en mí, y a veces me habla, o trae algo de merienda o bebida. Parece un hombre muy bueno."
    old " His wife visited the hospital. Though the Director and my lover prefer a simple and plain style, she dressed up too much, with luxurious dress and accessories. She looked just full of vanity. When I saw she's coquetting with him arm in arm, she really looked like an old fox. I can't imagine she's the Director's sister, and my lover's wife. She really makes me feel sick.\n\n When he and I were left alone because of night duty. he talked to me as if he was just working, because he knew we were being recorded on a CCTV.\n\n After finishing work, I got out of the hospital, and sat alone on the bench in front of the building. After a while, all lights were off in the hospital except one—Light from his office, coming through the blinds."
    new " Su esposa visitó el hospital. A pesar de que el director y mi amante prefieren un estilo simple y sencillo, se vistió, con un lujoso vestido y accesorios extravagantes. Parecía llena de vanidad. Cuando vi que coqueteaba con él de brazos, parecía una vieja zorra. No puedo imaginar que sea la hermana del director y la esposa de mi amante. Ella realmente me hace sentir enferma.\n\n Cuando él y yo nos quedamos solos debido al deber nocturno. Él me habló como si sólo estuviera trabajando, porque sabía que estábamos grabados en un CCTV.\n\n Después de terminar el trabajo, salí del hospital y me senté solo en el banco frente al edificio. Al cabo de un rato, todas las luces estaban apagadas en el hospital, excepto una luz de su oficina, que atravesaba las persianas."
    old " The director seemed to be trying hard not to hurt me, controlling his feelings. I understand he would feel betrayed as he has trusted me a lot, but he never swore at me at all, and treated me human to human. And now, I've finally realized what the hell I did. I felt really sorry for his wife, as she has never thought about this, and also felt sorry for the director who has always truly taken care of me. At the request of the Director, I decided to quit the hospital. I also said to him I would definitely break off my affair with the Doctor.\n\n After I packed up my stuff and got out of the hospital, I saw him running after me, but I just came out of the building and got into a taxi. In the running taxi, I just cried and cried. I could never see my colleagues there and the Director anymore…. and also him…. whom I made love with…. goodbye, everyone…. My greed has screwed up everything. Thank you all, and sorry…."
    new " El director parecía estar tratando de no hacerme daño, controlando sus sentimientos. Entiendo que se sentiría traicionado como él ha confiado mucho en mí, pero nunca me juró en absoluto, y me trató de humano a humano. Y ahora, finalmente me he dado cuenta de lo que hice. Sentí realmente pena por su esposa, ya que ella nunca ha pensado en esto, y también sentía lástima por el director que siempre ha cuidado de mí. A petición del Director, decidí dejar el hospital. También le dije que definitivamente rompería mi relación con el Doctor.\n\n Después de que tome mis cosas y salí del hospital, lo vi corriendo detrás de mí, pero salí del edificio y me metí en un taxi.\n\n En el taxi que corría, yo solo lloraba y lloraba. Nunca podría volver a ver a mis colegas allí y al Director.... y también a él.... con quien hice el amor.... adiós a todos…. Mi avaricia ha estropeado todo. Gracias a todos, y lo siento...."
    old " Every single day, I cry, sleep, and wake from sleep, remember my good old days, especially with him, and then, cry, and fall asleep again. Beginning with a few days ago, I sometimes burst into laughter, and sometimes, burst into a fit of anger. I feel like I can't breathe well from time to time.\n\n I miss him. I miss him looking at me with a gentle smile. Thinking this makes me weepy, and it becomes hard to breathe. Also at this moment I'm writing this, I'm feeling really suffocated."
    new " Cada día, lloro, duermo y despierto, recuerdo mis buenos viejos tiempos, especialmente con él, y luego, lloro y me duermo otra vez. Empezando con hace unos días, a veces me echaba a reír, y en ocasiones, se desataba un ataque de ira. Siento que no puedo respirar bien de vez en cuando.\n\n Le extraño. Le echo de menos mirándome con una sonrisa gentil. Pensar esto me hace llorar, y se hace difícil respirar. También en este momento estoy escribiendo esto, me siento realmente sofocada."
    old " Even though I had no interview today, I sat in front of my dressing table to put on makeup. But as soon as I saw my face, I was frightened, as it suddenly looked awful and disgusting. I fell backward, and managed to crawl to the bed. And I trembled and trembled. Then, I called Hye-na and begged her to save me.\n\n Soon, Hye-na came to my home, and I said to her I was probably going crazy, crying loudly in her arms. After I cried for a good while, I told her everything and taking her suggestion, I decided to see a doctor tomorrow. Hye-na is drinking a can of beer now.\n\n When I'm glancing at her, I feel my wrist, wrapped with bandages, is stinging.\n\n Okay, I'll finish today's diary here and go to bed after having some more conversations with Hye-na. Good night."
    new " A pesar de que no tenía ninguna entrevista hoy, me senté delante de mi tocador para ponerse el maquillaje. Pero tan pronto como vi mi cara, estaba asustada, ya que de pronto parecía horrible y repugnante. Me caí hacia atrás y logré arrastrarme hasta la cama. Y temblé y temblé. Entonces, llamé a Hye-na y le supliqué que me salvara.\n\n Pronto, Hye-na vino a mi casa, y le dije que probablemente estaba volviendo loca, llorando en sus brazos. Después de llorar por un buen rato, le dije todo y tomar su sugerencia, decidí ver a un médico mañana. Hye-na está bebiendo una lata de cerveza ahora.\n\n Cuando la estoy mirando, siento que mi muñeca, envuelta con vendajes, me duele.\n\n Bien, terminaré el diario de hoy aquí y me iré a la cama después de tener una charla más larga con Hye-na. Buenas noches."
    old " Today, I visited a neuropsychiatric clinic, with Hye-na. I was pretty afraid to go there, but as I was with my sister, I could do it. The doctor asked me a number of things, from trivial questions to what is happening to me now and what I don't want to tell others as well.\n\n He also asked whether I have some physical problems, and I told him I hurt myself several times, and especially when I looked at my face yesterday, I was really frightened, as my eyes continuously blinked. The doctor asked me to have a medical checkup. So I filled out the questionnaire and had a blood test as well.\n\n And the result said I had 'anxiety disorder' and 'depressive disorder'. I asked the doctor if I was going to be a mental patient. But he said no.\n\n He just told me my condition and tick disorder would get better soon, if I try hard to improve my life pattern and steadily get counseling."
    new " Hoy he visitado una clínica neuropsiquiátrica, con Hye-na. Tenía bastante miedo de ir allí, pero como estaba con mi hermana, podía hacerlo. El médico me hizo varias preguntas, desde preguntas triviales hasta lo que me está pasando ahora y lo que tampoco quiero decir a los demás.\n\n También me preguntó si tenía algunos problemas físicos, y le dije que me lastimé varias veces, y especialmente cuando miré mi cara ayer, estaba realmente asustado, mientras mis ojos parpadeaban continuamente. El médico me pidió que me hiciera un chequeo médico. Así que llené el cuestionario y me hicieron un análisis de sangre también.\n\n Y el resultado decía que tenía \"trastorno de ansiedad\" y \"trastorno depresivo\". Le pregunté al médico si iba a ser un paciente mental. Pero él dijo que no.\n\n Él sólo me dijo que mi condición y mis trastornos se pondrían mejor pronto, si me esfuerzo para mejorar mi patrón de vida y constantemente obtener asesoramiento."
    old " Today, I met Eunju. It's been a really long time since I've seen her. She used to be my best friend when we were high school students, but she is not single anymore. She said she's really worried as she hasn't lost any weight in spite of her steady diet since she gave birth to her baby. So I told her that she still looks good. Eunju worried about me saying I'm so bony, and she said to take her fat from her, shaking her potbelly. It was hilarious.\n\n Eunju has become a master of a Japanese fencing school. I think she probably heard about my situation from Hye-na, because she has never asked me about my job or marriage.\n\n She just kept talking about our school days, or her travel. Like other mamas, her voice was louder than it used to be, and also she speaks so fast Anyway, I'm happy she is having a good life.\n\n Ga-yeon, no more negative thinking! Okay?"
    new " Hoy conocí a Eunju. Ha pasado mucho tiempo desde que la he visto. Ella solía ser mi mejor amiga cuando éramos estudiantes de secundaria, pero ya no es soltera. Dijo que está muy preocupada porque no ha perdido peso a pesar de su dieta constante desde que dio a luz a su bebé. Así que le dije que todavía se ve bien. Eunju se preocupó por mí diciendo que soy tan huesuda, y ella dijo que le quitara la grasa, sacudiéndola. Fue hilarante.\n\n Eunju se ha convertido en una maestra de una escuela de esgrima japonesa. Creo que probablemente ella oyó hablar de mi situación de Hye-na, porque ella nunca me ha preguntado sobre mi trabajo o matrimonio.\n\n Sólo hablaba de nuestros días de escuela, o de su viaje. Al igual que otras mamás, su voz era más fuerte de lo que solía ser, y también ella habla tan rápido de todos modos, estoy feliz de que ella está teniendo una buena vida.\n\n ¡Ga-yeon, no más pensamiento negativo! ¿Bueno?"
    old " These days, I receive mental health treatment, and also try hard to get a job. I didn't want to close my installment savings account, but I did, to have some reserved money for myself and also give some of it to my parents. I can't stop sending money to my parents because I have to make them believe I live well without any problem as always.\n\n However, getting a new job is harder than I expected. Because I worked mostly in restaurants, I have failed several times already, although I had a number of interviews for general office jobs.\n\n Besides, I never wrote my mental health-related matter in the resume, but some interviewers seemed to recognize my problem, as my tick disorder appeared even during the interview.\n\n I'm trying really to keep the steam up, but…. I'm getting tired of living…."
    new " En estos días, recibo tratamiento de salud mental, y también me esfuerzo para conseguir un trabajo. No quería cerrar mi cuenta de ahorros a plazos, pero lo hice, para tener un poco de dinero reservado para mí y también dar parte de ello a mis padres. No puedo dejar de enviar dinero a mis padres porque tengo que hacerles creer que vivo bien sin ningún problema como siempre.\n\n Sin embargo, conseguir un nuevo trabajo es más difícil de lo que esperaba. Porque trabajé principalmente en restaurantes, he fallado varias veces ya, aunque tuve una serie de entrevistas para trabajos de oficina en general.\n\n Además, nunca escribí mi asunto relacionado con la salud mental en el currículum, pero algunos entrevistadores parecían reconocer mi problema, ya que mi trastorno de ansiedad apareció incluso durante la entrevista.\n\n Estoy tratando de mantener al día, pero... Me estoy cansando de vivir..."
    old " I gave up. I gave up finding a new job, meeting people, receiving medical treatment, and everything. All are just useless. What I have now is…. only this tiny space. Where nothing happens unless I stir it.\n\n In spite of heaps of attempts to get a job, what I had was only frustration and discouragement. The hospital where I've received the treatment suggested I transfer to another hospital. Sometimes, the nebulizer which Hye-na presented me to soothe myself didn't work at all.\n\n I feel like my room is a rubbish can, and I'm just rubbish."
    new " Me di por vencida. Dejé de buscar un nuevo trabajo, conocer gente, recibir tratamiento médico, y todo. Todos son inútiles. Lo que tengo ahora es.... sólo este pequeño espacio. Donde no pasa nada a menos que lo mueva.\n\n A pesar de los montones de intentos de conseguir un trabajo, lo que obtenía era sólo frustración y desánimo. El hospital donde recibí el tratamiento me sugirió que me trasladara a otro hospital. A veces, el nebulizador que Hye-na me presentaba para calmarme no funcionaba en absoluto.\n\n Me siento como mi habitación es un basurero, y yo soy sólo basura."
    old " Go die, you bitch. How dare you want to live on! You're such a hooker who tried to take another's husband! Why are you still alive? You know well what a useless thing you are. You're just a whore. Now are you going to cling to him, instead of your previous lover? You don't deserve to live anymore. Go away. Go away and die.\n\n Someone keeps whispering in my ears. Okay. Alright. Just stop it, please. Please. I'm sorry. I go and die now. So, please shut up!"
    new " Ve a morir, perra. ¡Cómo te atreves a vivir! ¡Eres una prostituta que trató de tomar marido de otro! ¿Por qué sigues viva? Sabes bien lo inútil que eres. Eres sólo una puta. ¿Ahora vas a aferrarte a él, en lugar de su amante anterior? Ya no mereces vivir. Vete. Vete y muere.\n\n Alguien sigue susurrando en mis oídos. Bueno. Bien. Solo para, por favor. Por favor. Lo siento. Voy a morir ahora. Así que…  ¡Por favor cállate!"
    old "Mouse"
    new "Ratón"
    old "Keyboard"
    new "Teclado"
    old "Gamepad"
    new "Mando"
    old "Left Click"
    new "Clic izquierdo"
    old "Advances dialogue and activates the interface."
    new "Avanza el diálogo y activa la interfaz."
    old "Right Click"
    new "Clic derecho"
    old "Accesses the game menu."
    new "Accede al menú del juego."
    old "Mouse Wheel Up\nClick Rollback Side"
    new "Rueda del ratón arriba\nClic en lado de retroceso"
    old "Rolls back to earlier dialogue."
    new "Retrocede al diálogo anterior."
    old "Mouse Wheel Down"
    new "Rueda del ratón abajo"
    old "Rolls forward to later dialogue."
    new "Avanza hacia el diálogo siguiente."
    old "Middle Click"
    new "Clic medio"
    old "Hides the user interface."
    new "Oculta la interfaz."
    old "Space"
    new "Espacio"
    old "Advances dialogue without selecting choices."
    new "Avanza el dilogo sin seleccionar opciones."
    old "Arrow Keys"
    new "Teclas de flecha"
    old "Navigate the interface."
    new "Navega la interfaz."
    old "Skips dialogue while held down."
    new "Salta el diálogo mientras se presiona."
    old "Tab"
    new "Tabulador"
    old "Toggles dialogue skipping."
    new "Activa/desactiva el salto de diálogo."
    old "Page Up"
    new "Av. pág."
    old "Page Down"
    new "Re. pág."
    old "Takes a screenshot."
    new "Captura la pantalla."
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new "Activa/desactiva la asistencia por {a=https://www.renpy.org/l/voicing}voz-automática{/a}."
    old "Start"
    new "Comenzar"
    old "Back"
    new "Atrás"
    old "Calibrate"
    new "Calibrar"
